services:
  backend:
    container_name: threetree-backend
    build:
      context: .
      dockerfile: DockerfileBackend
    ports:
      - "8080:8080"
    networks:
      - db
    restart: unless-stopped
    command: ./mvnw package

  #  frontend:
  #    container_name: threetree-frontend
  #    build: ../../frontend
  #    ports:
  #      - "3000:3000"
  #    networks:
  #      - db
  #    restart: unless-stopped
#
#  db:
#    container_name: threetree
#    image: postgres
#    environment:
#      POSTGRES_DB: customer
#      POSTGRES_USER: threetree
#      POSTGRES_PASSWORD: threetree
#      PGDATA: /data/postgres
#    volumes:
#      - db:/data/postgres
#    ports:
#      - "5532:5432"
#    networks:
#      - db
#    restart: unless-stopped
networks:
  db:
volumes:
  db:
