version: '3'
services:
  postgres:
    image: postgres:14
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: atidb
      POSTGRES_PASSWORD: atidb
    ports:
      - "5532:5532"
    volumes:
      - /path/to/local/data:/var/lib/postgresql/data
    networks:
      - db

  backend:
    container_name: threetree-backend
    build:
      context: .
      dockerfile: DockerfileBackend
    ports:
      - "8080:8080"
    networks:
      - db
    restart: unless-stopped
    command: ./mvnw package

networks:
  db: