services:
  db:
    container_name: threetree
    image: postgres
    environment:
      POSTGRES_DB: customer
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5532:5432"
    networks:
      - db
    restart: unless-stopped
networks:
  db:
volumes:
  db: