server:
  port: 8080

spring:

#  logging:
#    level:
#      com:
#        zaxxer:
#          hikari=${ERROR}:
#      org:
#        springframework=${INFO}:
#        hibernate=${ERROR}:

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/customer
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop #update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: false

  main:
    web-application-type: servlet
