server:
  port: 8080

spring:

  logging:
    level:
      com:
        zaxxer:
          hikari=${INFO}:
      org:
        springframework=${INFO}:
        hibernate=${INFO}:

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/customer
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: create-drop #update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true

  main:
    web-application-type: servlet
